### ISSUE TITLE
&nbsp; become &amp;nbsp;

### ISSUE THREAD

**Issue by afterbit01** [foundation/foundation-emails#841]
Hi,
when i use the inliner the entity "&nbsp;" become "&amp;nbsp;"
is it right?

**Comment by bartdevuyst** [comment]
I have the same issue with the inliner. Seems like a conversion bug between the HTML name and HTML number of a non-breaking space character. `&nbps;` vs. `&#160;`

**Comment by sollemar** [comment]
https://foundation.zurb.com/emails/inliner-v2.html
Same here

**Comment by julkue** [comment]
Same as #763

**Comment by DanielRuf** [comment]
Probably caused by html-minifier. Have to check this when I find some time.

**Comment by DanielRuf** [comment]
<img width="1244" alt="Bildschirmfoto 2020-01-31 um 01 32 32" src="https://user-images.githubusercontent.com/827205/73502532-98d7fa00-43c9-11ea-8418-952968542412.png">

**Comment by DanielRuf** [comment]
Not yet sure where exactly this is happening:

https://github.com/foundation/foundation-web-inliner/blob/master/lib/inline.js

**Comment by DanielRuf** [comment]
Seems it does not happen with the current status of the foundation-web-inliner project (chore/upgrade-browserify-html-minifier):


<img width="1042" alt="Bildschirmfoto 2020-01-31 um 01 45 41" src="https://user-images.githubusercontent.com/827205/73503092-819a0c00-43cb-11ea-9167-019304a77322.png">

https://github.com/foundation/foundation-web-inliner/pull/3

So this should be fixed with the next deployment.

**Comment by DanielRuf** [comment]
Old minifier from https://raw.githubusercontent.com/foundation/foundation-marketing/master/src/assets/lib/inliner.min.js

<img width="559" alt="Bildschirmfoto 2020-01-31 um 01 54 18" src="https://user-images.githubusercontent.com/827205/73503481-aa6ed100-43cc-11ea-8c80-3fef426e5249.png">

**Comment by DanielRuf** [comment]
I guess the html markup comes from cheerio

https://github.com/cheeriojs/cheerio/search?q=xhtml+is%3Aissue&type=Issues

**Comment by ghost** [comment]
This still seems to be an issue with the web-based inliner "copy to clipboard" button - &amp; gets changed to &amp;amp; by that button. Am wondering when the fix will be released - the last discussion was about a year ago.

Thanks.

**Comment by Peter-HVD** [comment]
This is still an issue. and it is definitely with the "copy to clipboard" button - if you manually select the code the ampersand is not encoded.

**Comment by joeworkman** [comment]
Fixed in Inky v2. The Rust rewrite uses the `css_inline` crate which handles HTML entities correctly without double-encoding.
